app = "kairos-worker"
primary_region = "fra"

[build]
  dockerfile = "../../base/Dockerfile"
  context    = "../.."

[processes]
  app = "python workers/kairos/main.py"

[deploy]
  min_machines_running = 1
