app = "kairos-worker"
primary_region = "fra"
context = "../.."

[build]
  dockerfile = "../../base/Dockerfile"

[build.args]
  ENTRYPOINT_WILL_BE_REPLACED = "workers/kairos/main.py"

[[vm]]
  cpu_kind = "shared"
  cpus     = 1
  memory   = "1gb"
