app = "spark-worker"
primary_region = "fra"

[build]
  dockerfile = "../../base/Dockerfile"

[build.args]
  ENTRYPOINT_WILL_BE_REPLACED = "workers/spark/main.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
