app = "content-ingestor-worker"
primary_region = "fra"

[build]
  dockerfile = "../../base/Dockerfile"
  context    = "../.."

[processes]
  app = "python -m workers.content_ingestor.main"

[env]
  QUEUE_USE_RPC = "false"

[deploy]
  min_machines_running = 1
