app = "napoleon-worker"
primary_region = "fra"

[build]
  dockerfile = "base/Dockerfile"
  context    = "../.."

command = ["python", "workers/napoleon/main.py"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
