app = "napoleon-worker"
primary_region = "fra"

[build]
  dockerfile = "base/Dockerfile"

[build.args]
  ENTRYPOINT_WILL_BE_REPLACED = "workers/napoleon/main.py"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
